Repository volcengine/veScale, pull requests merged in 2024-04, with the labels that each got.

#19 [CI] Add a basic ci test
  .github/workflows/ci.yaml
Labels: enhancement

#20 [DTensor & DModule & DOptim] feature updates
  python/example/nanogpt_4D_finetune/README.md
  python/example/nanogpt_4D_finetune/figures/nanoGPT_finetune_4d_forcebf16_train_loss_bf16_200.jpg
  python/example/nanogpt_4D_finetune/figures/nanoGPT_finetune_4d_forcebf16_val_loss_bf16_200.jpg
  python/example/nanogpt_4D_finetune/sharding_plan.py
  python/vescale/ddp/distributed_data_parallel.py
  python/vescale/ddp/grad_buffer.py
  python/vescale/dmodule/_dmodule.py
  python/vescale/dmodule/_grad_sync.py
  python/vescale/dmodule/_hook.py
  python/vescale/dmodule/placements_interface.py
  python/vescale/dtensor/__init__.py
  python/vescale/dtensor/_collective_utils.py
  python/vescale/dtensor/_dispatch_bypass.py
  python/vescale/dtensor/_dispatch_patch.py
  python/vescale/dtensor/_utils.py
  python/vescale/dtensor/api.py
  python/vescale/dtensor/dispatch.py
  python/vescale/dtensor/dtensor.py
  python/vescale/dtensor/ops/embedding_ops.py
  python/vescale/dtensor/ops/math_ops.py
  python/vescale/dtensor/ops/pointwise_ops.py
  python/vescale/dtensor/ops/random_ops.py
  python/vescale/dtensor/ops/tensor_ops.py
  python/vescale/dtensor/ops/utils.py
  python/vescale/dtensor/ops/view_ops.py
  python/vescale/dtensor/redistribute.py
  python/vescale/initialize/deferred_init.py
  python/vescale/optim/base_optimizer.py
  python/vescale/optim/distributed_optimizer.py
  test/dmodule/test_plans.py
  test/dtensor/general/test_api.py
  test/dtensor/general/test_dtensor.py
  test/dtensor/ops/test_math_ops.py
  test/dtensor/ops/test_pointwise_ops.py
  test/dtensor/ops/test_tensor_ops.py
  test/parallel/ddp_optim/test_clip_grads.py
  test/parallel/ddp_optim/test_ddp.py
  test/parallel/ddp_optim/test_grad_sync.py
Labels: enhancement

#22 [Example] add an example of running open llama model in 4D using veScale
  python/example/open_llama_4D_benchmark/README.md
  python/example/open_llama_4D_benchmark/config.json
  python/example/open_llama_4D_benchmark/download_open_llama_ckpt.py
  python/example/open_llama_4D_benchmark/llama_mfu_calculator.py
  python/example/open_llama_4D_benchmark/run_open_llama_w_vescale.py
  python/example/open_llama_4D_benchmark/sharding_plan.py
  test/model/open_llama/config.json
  test/model/open_llama/test_attention.py
  test/model/open_llama/test_decoder_layer.py
  test/model/open_llama/test_mlp.py
  test/model/open_llama/test_open_llama.py
  test/model/open_llama/test_rms_norm.py
Labels: documentation, enhancement

#23 [DTensor]: remove sharding_spec.py
  python/vescale/dtensor/sharding_spec.py
Labels: enhancement

#27 [checkpoint] Open Source
  .gitignore
  python/example/nanogpt_4D_finetune/README.md
  python/example/nanogpt_4D_finetune/finetune_4D.py
  python/vescale/__init__.py
  python/vescale/checkpoint/README.md
  python/vescale/checkpoint/__init__.py
  python/vescale/checkpoint/api/base_checkpointer.py
  python/vescale/checkpoint/api/meta_type.py
  python/vescale/checkpoint/api/vescale_checkpointer.py
  python/vescale/checkpoint/load_state_dict.py
  python/vescale/checkpoint/planner/vescale/__init__.py
  python/vescale/checkpoint/planner/vescale/vescale_planner.py
  python/vescale/checkpoint/planner/vescale/vescale_planner_helpers.py
  python/vescale/checkpoint/save_state_dict.py
  python/vescale/checkpoint/storage/checkpoint_adapter.py
  python/vescale/checkpoint/storage/checkpoint_format.py
  python/vescale/checkpoint/utilities/bfile.py
  python/vescale/checkpoint/utilities/logger.py
  python/vescale/checkpoint/utilities/mem_checkpoint.py
  python/vescale/checkpoint/utilities/server/__init__.py
  python/vescale/checkpoint/utilities/server/detached_mem_server.py
  python/vescale/checkpoint/utilities/server/mem_file_service.proto
  python/vescale/checkpoint/utilities/server/mem_file_service_pb2.py
  python/vescale/checkpoint/utilities/server/mem_file_service_pb2.pyi
  python/vescale/checkpoint/utilities/server/mem_file_service_pb2_grpc.py
  python/vescale/checkpoint/utilities/server/mem_server_lib.py
  python/vescale/checkpoint/utilities/server/report_service.proto
  python/vescale/checkpoint/utilities/server/report_service_pb2.py
  python/vescale/checkpoint/utilities/server/report_service_pb2.pyi
  python/vescale/checkpoint/utilities/server/report_service_pb2_grpc.py
  python/vescale/checkpoint/utilities/server/server_lib.py
  python/vescale/checkpoint/utilities/server/server_status_client.py
  python/vescale/checkpoint/utilities/sync_queue.py
  python/vescale/checkpoint/version.py
  scripts/run_test.sh
  test/checkpoint/__init__.py
  test/checkpoint/common_func.py
  test/checkpoint/nano_gpt.py
  test/checkpoint/nano_gpt/test_nano_gpt_load_save.py
  test/checkpoint/open_llama/__init__.py
  test/checkpoint/open_llama/test_open_llama_dp_reshard.py
  test/checkpoint/open_llama/test_open_llama_load_save.py
  test/checkpoint/open_llama/test_open_llama_tp_reshard.py
Labels: enhancement

#29 [PyTorch] Add patches for distributed randomness
  patches/patched_pytorch_v2.2.1_rc3.patch
Labels: bug, enhancement
